baseURL = 'https://robertweijie.github.io/'
languageCode = 'zh-cn'
title = 'Welcome to my world'
theme = 'PaperMod'

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[languages.en.menu.main]]
name = "Archive"
url = "archives"
weight = 5

[[languages.en.menu.main]]
name = "Search"
url = "search/"
weight = 10

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10


[languages.cn]
languageName = ":cn:"
weight = 1
title = "ä¼Ÿæ°çš„åšå®¢"


[[languages.cn.menu.main]]
name = "æ ‡ç­¾"
url = "cntags"
weight = 10





  [languages.cn.params]
  languageAltTitle = "ä¸­æ–‡"

    [languages.cn.params.profileMode]
    enabled = true
    title = "æ¬¢è¿ï¼ï¼"
    imageUrl = "img/demo.png" # æ›¿æ¢ä¸ºå®é™…çš„å›¾ç‰‡é“¾æ¥
    imageTitle = "ä¸ªäººèµ„æ–™å›¾ç‰‡"
    subtitle = "âš¡ï¸ å¿«é€Ÿ | ğŸƒ æµç•… | ğŸŒœ ä¼˜é›… | ğŸ“± å“åº”å¼"

      [[languages.cn.params.profileMode.buttons]]
      name = "åšå®¢"
      url = "/Chinese/"


      [[languages.cn.params.profileMode.buttons]]
      name = "å…³äº"
      url = "/about/" # æ›¿æ¢ä¸ºå®é™…çš„é“¾æ¥

[languages.es]
languageName = ":es:"
weight = 1
title = "El Blog de Roberto"

  [languages.es.taxonomies]
  category = "EScategorias"
  tag = "EStags"
  series = "ESseries"



[[languages.es.menu.main]]
name = "Etiquetas"
url = "etiquetas/"
weight = 10



  [languages.es.params]
  languageAltTitle = "EspaÃ±ol"

    [languages.es.params.profileMode]
    enabled = true
    title = "El Blog de Roberto"
    imageUrl = "img/demo.png" # Reemplaza con el enlace de tu imagen
    imageTitle = "Foto de perfil"
    subtitle = "âš¡ï¸ RÃ¡pido | ğŸƒ Fluido | ğŸŒœ Elegante | ğŸ“± Responsive"

      [[languages.es.params.profileMode.buttons]]
      name = "Blog"
      url = "blog/"

      [[languages.es.params.profileMode.buttons]]
      name = "Modo Perfil"
      url = "https://github.com/adityatelange/hugo-PaperMod/wiki/Features#profile-mode" 




[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
author = "Me"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
images = [ "images/papermod-cover.png" ]

  [params.profileMode]
  enabled = false
  title = "PaperMod"
  imageUrl = "#"
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Archives"
    url = "archives"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Robert BlogğŸ‡¨ğŸ‡³ğŸ‡µğŸ‡¦"
  Content = """
ğŸ‘‹ Here, I will share my daily life, whether it's technology, life, or any insightsï¼ŒAnyway, thank you again for watching!!ğŸ‘
"""

  [[params.socialIcons]]
  name = "github"
  title = "View Source on Github"
  url = "https://github.com/RobertWeijie"

  [[params.socialIcons]]
  name = "Discord"
  title = "Join discord community"
  url = "https://discord.gg/eyyEmRjY8A"

  [[params.socialIcons]]
  name = "Reddit"
  title = "Share PaperMod on X/Twitter"
  url = "https://www.reddit.com/user/TechPlaza24/"

  [[params.socialIcons]]
  name = "instagram"
  title = "Share PaperMod on instagram"
  url = "https://www.instagram.com/parobket/?next=%2F"




  [params.editPost]
  URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true





